# coding:utf-8

- hosts: all
  sudo: yes

  handlers:

  - name: update tzdata
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata


  tasks:

  - name: install and upgrade all packages
    apt: name={{ item }} state=present update_cache=yes
    with_items:
        - git
        - language-pack-ja
        - byobu

  - name: locale setting
    shell: 'update-locale LANG=ja_JP.UTF-8'

  - name: Set timezone variables
    copy: content='Asia/Tokyo\n' dest=/etc/timezone backup=yes
    notify: update tzdata

  - name: firewall(ufw) settings
    include: tasks/firewall.yml

  # DDNS sync script install

  - name: DDNS sync script upload
    copy:
      src: ./resources/ieserver-ddns.pl
      dest: /etc/cron.hourly/ieserver-ddns.pl
      backup: yes

  - name: DDNS sync script chenge user and mode
    shell: 'chown root:root /etc/cron.hourly/ieserver-ddns.pl && chmod 777 /etc/cron.hourly/ieserver-ddns.pl'
