# Docker install.

- name: apt-get install packages
  apt:
    pkg: '{{item}}'
    state: present
    update_cache: yes
  with_items:
    - docker.io
    - curl

- name: Docker with SUID.
  file:
    path: /usr/bin/docker
    mode: 'u+s'
