# coding:utf-8

# Firewall(ufw) settings.
# (only abaut ufw writing.)

- name: clear and all deny
  ufw: state=enabled policy=reject

- name: Allow ssh
  ufw: rule=allow port=ssh

- name: Allow Dotnet Core Application
  ufw: 
    rule: allow 
    port: 5000
    proto: tcp

- name: Allow some Docker Application.
  ufw: 
    rule: allow
    port: 8000:8999 
    proto: tcp

# TODO インストールされたら

#- name: Allow http
#  ufw: rule=allow port=http

#- name: Allow https
#  ufw: rule=allow port=https
