# coding:utf-8

# for Ubuntu 14.04.1 LTS (-> Ubuntu 16.04.3 upgrade)  in cloudatcost

- hosts: all
  sudo: yes

  handlers:

  - name: update tzdata
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

  tasks:

  - name: change hostname per server
    hostname: name="{{ inventory_hostname }}"

  - name: install and upgrade all packages
    apt: name={{ item }} state=present update_cache=yes
    with_items:
        - git
        - language-pack-ja
        - byobu
        - mongodb-clients
        - jq

  - name: locale setting
    shell: 'update-locale LANG=ja_JP.UTF-8'

  - name: Set timezone variables
    timezone:
      name: Asia/Tokyo

  - name: Setting swap file
    include: tasks/swap.yml

  - name: firewall(ufw) settings
    include: tasks/firewall.yml

  - name: Docker install
    include: tasks/docker.yml
