docker_on_jenkins_on_docker:
  image: getintodevops/jenkins-withdocker:lts
  ports:
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  container_name: dojod-jenkins-container
  restart: "unless-stopped"
