# coding:utf-8
# for Debian 10

- hosts: all
  become: yes
  become_user: root

  vars:
    raid_dev: /dev/md0
    raid_level: 1
    raid_name: RAID
    raid_mount: /home
    bench_file: /root/output.html

  tasks:

  - block:

    - name: システム全更新。
      apt:
        update_cache: "yes"
        upgrade: "dist"

    - name: 必要なツールをインストール。
      apt:
        name:
          - tree
          - byobu
          - vim
          - ntp
          - parted
          - mdadm

  - block:

    # - name: ネットワーク設定ファイルを反映。
    #   copy: 
    #     src: resources/etc/network/interfaces
    #     dest: /etc/network/interfaces
    #     backup: yes

    - name: ホスト名設定。
      hostname:
        name: fumiko

  - block:

    - name: NTP設定ファイルを反映。
      copy: 
        src: resources/etc/ntp.conf
        dest: /etc/ntp.conf
        backup: yes

    - name: NTPサービス再起動。
      systemd:
        name: ntp.service
        state: restarted
        daemon_reload: yes
        enabled: yes

  - block:
    
    - name: すでにRAIDが構築されているかを確認。
      shell: ls {{ raid_dev }}
      register: sh_ls_raid_dev
      failed_when: no

    - name: RAIDデバイス作成。
      shell: yes | mdadm --create --verbose "{{ raid_dev }}" --level="{{ raid_level }}" --name="{{ raid_name }}" --raid-devices=2 /dev/sdb /dev/sdc
      when: sh_ls_raid_dev.stdout_lines.count("{{ raid_dev }}") == 0

    - name: ファイルシステムの確認 {{ raid_dev }}
      shell: parted -l | grep "{{ raid_dev }}"
      register: sh_parted_l
      failed_when: no

    - name: RAID1のデバイスにEXT4のファイルシステムを作成。
      shell: mkfs.ext4 -L "{{ raid_name }}" "{{ raid_dev }}"
      when: sh_parted_l.stdout_lines.count("unrecognised disk label") != 0

    - name: 元のHomeを退避する
      shell: df | grep '/dev/md0' | grep '/home' || cp -ar /home /home_taihi

    - name: マウント用のディレクトリを作成する。
      file:
        state: directory
        path: "{{ raid_mount }}"
        owner: root
        group: root
        mode: '0755'

    - name: RAID1デバイスをマウント。
      mount:
        name: "{{ raid_mount }}"
        src: "{{ raid_dev }}"
        fstype: ext4
        state: mounted

    - name: 退避しているディレクトリが在る場合は中身を移動し削除。
      shell:  '[ ! -d /home_taihi ] || ( cp -ar /home_taihi/* /home/ && rm -rf /home_taihi/ )'