# coding:utf-8
# for Debian 10

- hosts: all
  become: yes
  become_user: root

  tasks:

  - block:

    - name: システム全更新。
      apt:
        update_cache: "yes"
        upgrade: "dist"

    - name: 必要なツールをインストール。
      apt:
        name:
          - tree
          - byobu
          - vim
          - ntp

  - block:

    # - name: ネットワーク設定ファイルを反映。
    #   copy: 
    #     src: resources/etc/network/interfaces
    #     dest: /etc/network/interfaces
    #     backup: yes

    - name: ホスト名設定。
      hostname:
        name: fumiko
