# coding:utf-8

# sonarqubeの「DBの設定」だけを行う。

# sonarqube だけは「何も見せないような未ログイン」が無い。
# 一時的な対策として「Nginxを入り口にしてbasic認証かけとく」とする
# TODO 見直し、(Jenkins,Nexusも含めた)統合的なセキュリティ対策
# TODO 見直し、上記を含め「代表的なURL」を仕込み直し
#
#  docker run --name nginx -v /var/local/nginx_conf.d:/etc/nginx/conf.d -v /var/local/yum_repo:/var/local/yum_repo -v /etc/letsencrypt:/etc/nginx/letsencrypt -p 80:80 -p 443:443 --restart=always -d  nginx

- name: nginxの設定ファイルを一式を配置
  copy:
    src: ./resources/nginx_conf.d/
    dest: /var/local/nginx_conf.d/

- name: LetsEncriptの自動SSL更新ツールをインストール
  copy:
    src: ./resources/letsencrypt/
    dest: /var/local/letsencrypt/

- name: 自動更新ツールに実行権限を付与
  file: path=/var/local/letsencrypt/certbot-auto-monthry.sh owner=root group=root mode=755

- name: 自動更新ツールcertbotのディレクトリを予め削除
  shell: 'rm -rf /var/local/letsencrypt/certbot/'

- name: githubから自動更新ツールceartbot一式をダウンロード
  shell: 'cd /var/local/letsencrypt/ && git clone --depth 1 https://github.com/certbot/certbot'

- name: certbotが依存するツール群を収集
  shell: 'cd /var/local/letsencrypt/certbot/ && ./certbot-auto -n'

- name: nginxのDockerコンテナを起動
  docker:
    image: nginx
    name: nginx
    ports: 80:80,443:443
    volumes: /var/local/nginx_conf.d:/etc/nginx/conf.d,/var/local/yum_repo:/var/local/yum_repo,/etc/letsencrypt:/etc/nginx/letsencrypt
    detach: yes
    tty: yes
    restart_policy: unless-stopped
    state: running
